### ISSUE TITLE
🎨 Migrate to twenty-ui

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/core-team-issues#144]
## Scope & Context

Twenty UI migration

For now we have multiple components that are tied to twenty-front, Recoil and performance testing is something we will probably need to keep out of twenty-ui, so for now we'll just migrate what's already stateless, which already represents a big chunk of the ui/ folder.

See https://github.com/twentyhq/core-team-issues/issues/185 for challenges on other components in ui/ folder that are not extracted for now.

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/private-issues/issues/88
- [ ] https://github.com/twentyhq/private-issues/issues/84
- [ ] https://github.com/twentyhq/private-issues/issues/83
- [ ] https://github.com/twentyhq/private-issues/issues/80
- [ ] https://github.com/twentyhq/private-issues/issues/78
```

**Comment by ijreilly** [comment]
@gitstart-twenty For this issue please open PRs folder by folder and not a big PR with a lot at once, otherwise we will have too much conflicts
