### ISSUE TITLE
Refactor Record Filter and Record Sort

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/core-team-issues#40]
## Master issue for the refactor of record filters and record sorts.

Goals of this refactor :

- Remove component state v1 from record filter and record sort states.
- Progressively rollout a V2 handling of record filters and record sorts that is acting in parallel, so we only have to switch to V2 from V1 without breaking anything
- Have record filters and record sorts act as standalone modules and also standalone contexts, that can be used by other related modules : index, table, kanban, view, context store.

ViewFilter and RecordFilter are two concepts that are used in the view module. 

They are required to keep the database ViewFilter concept and the UI Filter concept separated, but right now we could have a better abstraction of ViewFilter.

Because in the UI we manipulate almost always RecordFilters, and we could have it turned into ViewFilter and back again so that we never manipulate ViewFilter directly.

- [x] twentyhq/twenty#9399
- [x] twentyhq/core-team-issues#42
- [x] twentyhq/core-team-issues#41
- [x] twentyhq/core-team-issues#39
- [x] #263
- [x] #264
- [x] #265
- [x] #266
- [x] #267
- [x] #268
- [x] #270
- [x] https://github.com/twentyhq/twenty/issues/9551

**Comment by ad-elias** [comment]
Could I work on this!

**Comment by FelixMalfait** [comment]
Great thanks a lot Elias! You can work on that in November when you come back that'd be great!

**Comment by lucasbordeau** [comment]
@FelixMalfait @ad-elias I'll take it because we need to be very precise about it with @charlesBochet and we already discussed implementation details, also I'll be refactoring related things this sprint.

**Comment by FelixMalfait** [comment]
Perfect thank you @lucasbordeau
